#! /usr/bin/env python
#
# When not running on the local host: Use SSH with port forwarding to the port reported when
# you start this script (8888 unless the script has been modified): -L 8888:localhost:8888.

import SimpleHTTPServer
import SocketServer
import mimetypes

PORT = 8888

Handler = SimpleHTTPServer.SimpleHTTPRequestHandler

Handler.extensions_map['.svg']='image/svg+xml'
httpd = SocketServer.TCPServer(("", PORT), Handler)

print "serving at port", PORT
httpd.serve_forever()
